[package]
name = "q4"
version = "0.1.0"
authors = ["tymoore <tymoore@ualberta.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
